#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: validate
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        format_sql: true
#    show-sql: true

#分页
pagehelper:
  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

#数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.193.94:3306/blogdb?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  #es
  elasticsearch:
    jest:
      url: http://changyue.club:9201/
      connection-timeout: 20000
      read-timeout: 20000
#mybatis
mybatis:
  type-aliases-package: com.changyue.blogserver.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    #开启sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#redis
redis:
  host: ${spring.redis.host}
  port: ${spring.redis.port}
  timeout: ${spring.redis.timeout}
  password: ${spring.redis.password}

